Module Module_language
    Public local_language As String = "en"
    Public Sub change_language(ByVal language As String)
        Select Case language
            Case "ch"
                'Mainform.Text = "核型和性状分析"
                'Mainform.MenuItem1.Text = "文件"
                'Mainform.MenuItem2.Text = "打开"
                'Mainform.MenuItem5.Text = "照片"
                'Mainform.MenuItem4.Text = "文档"
                'Mainform.MenuItem3.Text = "保存"
                'Mainform.MenuItem24.Text = "保存文件"
                'Mainform.MenuItem25.Text = "保存结果"
                'Mainform.MenuItem27.Text = "保存照片"
                'Mainform.MenuItem28.Text = "保存所有"
                'Mainform.MenuItem29.Text = "只保存ID"
                'Mainform.MenuItem14.Text = "新建"
                'Mainform.MenuItem15.Text = "退出"
                'Mainform.MenuItem32.Text = "工具"
                'Mainform.MenuItem8.Text = "分析"
                'Mainform.MenuItem10.Text = "分型"
                'Mainform.MenuItem36.Text = "标尺"
                'Mainform.MenuItem39.Text = "合并结果"
                'Mainform.MenuItem33.Text = "测量性状"
                'Mainform.MenuItem6.Text = "视图"
                'Mainform.MenuItem23.Text = "刷新"
                'Mainform.MenuItem30.Text = "顶置"
                'Mainform.MenuItem18.Text = "显示"
                'Mainform.MenuItem31.Text = "组编号"
                'Mainform.MenuItem20.Text = "网格"
                'Mainform.MenuItem19.Text = "坐标"
                'Mainform.MenuItem17.Text = "颜色"
                'Mainform.MenuItem16.Text = "字体"
                'Mainform.MenuItem13.Text = "线条"
                'Mainform.MenuItem9.Text = "工具箱"
                'Mainform.MenuItem7.Text = "数据箱"
                'Mainform.MenuItem12.Text = "帮助"
                'Mainform.MenuItem22.Text = "关于"
                'Mainform.MenuItem26.Text = "帮助"
                'Toolform.ToolBarButton1.Text = "长度"
                'Toolform.ToolBarButton7.Text = "面积"
                'Toolform.ToolBarButton2.Text = "新建"
                'Toolform.ToolBarButton3.Text = "删除"
                'Toolform.ToolBarButton4.Text = "放大"
                'Toolform.ToolBarButton5.Text = "缩小"
                'Toolform.ToolBarButton6.Text = "分型"
                'Dataform.Label3.Text = "长度"
                'Dataform.Text = "数据箱"
                'Dataform.Button1.Text = "臂长1"
                'Dataform.Button2.Text = "臂长2"
                'Dataform.RadioButton1.Text = "无随体"
                'Dataform.RadioButton2.Text = "长臂随体"
                'Dataform.RadioButton3.Text = "短臂随体"
                'Dataform.RadioButton4.Text = "居间随体"
                Analysisform.Text = "分型结果"
                Analysisform.FileToolStripMenuItem.Text = "文件"
                Analysisform.SaveToolStripMenuItem.Text = "保存"
                Analysisform.SaveGraphicToolStripMenuItem.Text = "保存图像"
                Analysisform.SaveResultToolStripMenuItem.Text = "保存结果"
                Analysisform.ViewToolStripMenuItem.Text = "查看"
                Analysisform.IdiogramToolStripMenuItem.Text = "分型图"
                Analysisform.GroupBox1.Text = "手动调整"
                Analysisform.Button1.Text = "交换"
                Analysisform.Label1.Text = "缩放"
            Case Else
        End Select
    End Sub
End Module
